title: Dew Drops
author: SwaJos
email: admin@influenshine.com
description: > # this means to ignore newlines until "baseurl:"
  This page is about my journey towards learning to code and how I built my second career.

# social links
twitter_username: iamswatijoshi
github_username:  swajos

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
